candlestick_patterns = {
    'CDL2CROWS': 'Two Crows',
    'CDL3BLACKCROWS': 'Three Black Crows',
    'CDL3INSIDE': 'Three Inside Up/Down',
    'CDL3LINESTRIKE': 'Three-Line Strike',
    'CDL3OUTSIDE': 'Three Outside Up/Down',
    'CDL3STARSINSOUTH': 'Three Stars In The South',
    'CDL3WHITESOLDIERS': 'Three Advancing White Soldiers',
    'CDLABANDONEDBABY': 'Abandoned Baby',
    'CDLADVANCEBLOCK': 'Advance Block',
    'CDLBELTHOLD': 'Belt-hold',
    'CDLBREAKAWAY': 'Breakaway',
    'CDLCLOSINGMARUBOZU': 'Closing Marubozu',
    'CDLCONCEALBABYSWALL': 'Concealing Baby Swallow',
    'CDLCOUNTERATTACK': 'Counterattack',
    'CDLDARKCLOUDCOVER': 'Dark Cloud Cover',
    'CDLDOJI': 'Doji',
    'CDLDOJISTAR': 'Doji Star',
    'CDLDRAGONFLYDOJI': 'Dragonfly Doji',
    'CDLENGULFING': 'Engulfing Pattern',
    'CDLEVENINGDOJISTAR': 'Evening Doji Star',
    'CDLEVENINGSTAR': 'Evening Star',
    'CDLGAPSIDESIDEWHITE': 'Up/Down-gap side-by-side white lines',
    'CDLGRAVESTONEDOJI': 'Gravestone Doji',
    'CDLHAMMER': 'Hammer',
    'CDLHANGINGMAN': 'Hanging Man',
    'CDLHARAMI': 'Harami Pattern',
    'CDLHARAMICROSS': 'Harami Cross Pattern',
    'CDLHIGHWAVE': 'High-Wave Candle',
    'CDLHIKKAKE': 'Hikkake Pattern',
    'CDLHIKKAKEMOD': 'Modified Hikkake Pattern',
    'CDLHOMINGPIGEON': 'Homing Pigeon',
    'CDLIDENTICAL3CROWS': 'Identical Three Crows',
    'CDLINNECK': 'In-Neck Pattern',
    'CDLINVERTEDHAMMER': 'Inverted Hammer',
    'CDLKICKING': 'Kicking',
    'CDLKICKINGBYLENGTH': 'Kicking - bull/bear determined by the longer marubozu',
    'CDLLADDERBOTTOM': 'Ladder Bottom',
    'CDLLONGLEGGEDDOJI': 'Long Legged Doji',
    'CDLLONGLINE': 'Long Line Candle',
    'CDLMARUBOZU': 'Marubozu',
    'CDLMATCHINGLOW': 'Matching Low',
    'CDLMATHOLD': 'Mat Hold',
    'CDLMORNINGDOJISTAR': 'Morning Doji Star',
    'CDLMORNINGSTAR': 'Morning Star',
    'CDLONNECK': 'On-Neck Pattern',
    'CDLPIERCING': 'Piercing Pattern',
    'CDLRICKSHAWMAN': 'Rickshaw Man',
    'CDLRISEFALL3METHODS': 'Rising/Falling Three Methods',
    'CDLSEPARATINGLINES': 'Separating Lines',
    'CDLSHOOTINGSTAR': 'Shooting Star',
    'CDLSHORTLINE': 'Short Line Candle',
    'CDLSPINNINGTOP': 'Spinning Top',
    'CDLSTALLEDPATTERN': 'Stalled Pattern',
    'CDLSTICKSANDWICH': 'Stick Sandwich',
    'CDLTAKURI': 'Takuri (Dragonfly Doji with very long lower shadow)',
    'CDLTASUKIGAP': 'Tasuki Gap',
    'CDLTHRUSTING': 'Thrusting Pattern',
    'CDLTRISTAR': 'Tristar Pattern',
    'CDLUNIQUE3RIVER': 'Unique 3 River',
    'CDLUPSIDEGAP2CROWS': 'Upside Gap Two Crows',
    'CDLXSIDEGAP3METHODS': 'Upside/Downside Gap Three Methods'
}


candlestick_patterns_func = {
    'Two Crows': 'CDL2CROWS',
    'Three Black Crows': 'CDL3BLACKCROWS',
    'Three Inside Up/Down': 'CDL3INSIDE',
    'Three-Line Strike': 'CDL3LINESTRIKE',
    'Three Outside Up/Down': 'CDL3OUTSIDE',
    'Three Stars In The South': 'CDL3STARSINSOUTH',
    'Three Advancing White Soldiers': 'CDL3WHITESOLDIERS',
    'Abandoned Baby': 'CDLABANDONEDBABY',
    'Advance Block': 'CDLADVANCEBLOCK',
    'Belt-hold': 'CDLBELTHOLD',
    'Breakaway': 'CDLBREAKAWAY',
    'Closing Marubozu': 'CDLCLOSINGMARUBOZU',
    'Concealing Baby Swallow': 'CDLCONCEALBABYSWALL',
    'Counterattack': 'CDLCOUNTERATTACK',
    'Dark Cloud Cover': 'CDLDARKCLOUDCOVER',
    'Doji': 'CDLDOJI',
    'Doji Star': 'CDLDOJISTAR',
    'Dragonfly Doji': 'CDLDRAGONFLYDOJI',
    'Engulfing Pattern': 'CDLENGULFING',
    'Evening Doji Star': 'CDLEVENINGDOJISTAR',
    'Evening Star': 'CDLEVENINGSTAR',
    'Up/Down-gap side-by-side white lines': 'CDLGAPSIDESIDEWHITE',
    'Gravestone Doji': 'CDLGRAVESTONEDOJI',
    'Hammer': 'CDLHAMMER',
    'Hanging Man': 'CDLHANGINGMAN',
    'Harami Pattern': 'CDLHARAMI',
    'Harami Cross Pattern': 'CDLHARAMICROSS',
    'High-Wave Candle': 'CDLHIGHWAVE',
    'Hikkake Pattern': 'CDLHIKKAKE',
    'Modified Hikkake Pattern': 'CDLHIKKAKEMOD',
    'Homing Pigeon': 'CDLHOMINGPIGEON',
    'Identical Three Crows': 'CDLIDENTICAL3CROWS',
    'In-Neck Pattern': 'CDLINNECK',
    'Inverted Hammer': 'CDLINVERTEDHAMMER',
    'Kicking': 'CDLKICKING',
    'Kicking - bull/bear determined by the longer marubozu': 'CDLKICKINGBYLENGTH',
    'Ladder Bottom': 'CDLLADDERBOTTOM',
    'Long Legged Doji': 'CDLLONGLEGGEDDOJI',
    'Long Line Candle': 'CDLLONGLINE',
    'Marubozu': 'CDLMARUBOZU',
    'Matching Low': 'CDLMATCHINGLOW',
    'Mat Hold': 'CDLMATHOLD',
    'Morning Doji Star': 'CDLMORNINGDOJISTAR',
    'Morning Star': 'CDLMORNINGSTAR',
    'On-Neck Pattern': 'CDLONNECK',
    'Piercing Pattern': 'CDLPIERCING',
    'Rickshaw Man': 'CDLRICKSHAWMAN',
    'Rising/Falling Three Methods': 'CDLRISEFALL3METHODS',
    'Separating Lines': 'CDLSEPARATINGLINES',
    'Shooting Star': 'CDLSHOOTINGSTAR',
    'Short Line Candle': 'CDLSHORTLINE',
    'Spinning Top': 'CDLSPINNINGTOP',
    'Stalled Pattern': 'CDLSTALLEDPATTERN',
    'Stick Sandwich': 'CDLSTICKSANDWICH',
    'Takuri (Dragonfly Doji with very long lower shadow)': 'CDLTAKURI',
    'Tasuki Gap': 'CDLTASUKIGAP',
    'Thrusting Pattern': 'CDLTHRUSTING',
    'Tristar Pattern': 'CDLTRISTAR',
    'Unique 3 River': 'CDLUNIQUE3RIVER',
    'Upside Gap Two Crows': 'CDLUPSIDEGAP2CROWS',
    'Upside/Downside Gap Three Methods': 'CDLXSIDEGAP3METHODS',
}